# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          # Maven details
          - mvn --version
        
          # Common Dependencies
          - cd Common
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # GraphPersist Dependencies
          - cd ../GraphPersist
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # TreeView Dependencies
          - cd ../TreeView
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # MatrixView Dependencies
          - cd ../MatrixView
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # FlowTree Dependencies
          - cd ../FlowTree
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # OptimalZoo Dependencies
          - cd ../OptimalZoo
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # Rings Dependencies
          - cd ../Rings
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # PhotonField Dependencies
          - cd ../PhotonField
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # ArtifactDetector Dependencies
          - cd ../ArtifactDetector
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # Replicator Dependencies
          - cd ../Replicator
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # Explorer Dependencies
          - cd ../Explorer
          - mvn dependency:copy-dependencies
          - mvn install
          
          
          # FeedGrowth Dependencies
          - cd ../FeedGrowth
          - mvn dependency:copy-dependencies
          - mvn install
